version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - app-network

  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/emails_db
      - SECRET_KEY=secret_key
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
